// Mock data for demonstration purposes

export const mockTeams = [
  {
    id: 'team1',
    name: 'Mechanics',
    description: 'Mechanical repairs and maintenance',
    members: [
      { id: 'user1', name: 'John Smith', email: 'john@company.com', role: 'Lead Technician' },
      { id: 'user2', name: 'Sarah Johnson', email: 'sarah@company.com', role: 'Technician' },
    ],
    color: '#3b82f6',
  },
  {
    id: 'team2',
    name: 'Electricians',
    description: 'Electrical systems and installations',
    members: [
      { id: 'user3', name: 'Mike Davis', email: 'mike@company.com', role: 'Senior Electrician' },
      { id: 'user4', name: 'Emily Brown', email: 'emily@company.com', role: 'Electrician' },
    ],
    color: '#f59e0b',
  },
  {
    id: 'team3',
    name: 'IT Support',
    description: 'Computer and network maintenance',
    members: [
      { id: 'user5', name: 'Alex Wilson', email: 'alex@company.com', role: 'IT Specialist' },
      { id: 'user6', name: 'Rachel Green', email: 'rachel@company.com', role: 'IT Technician' },
    ],
    color: '#10b981',
  },
];

export const mockEquipment = [
  {
    id: 'eq1',
    name: 'CNC Machine #1',
    serialNumber: 'CNC-2024-001',
    category: 'Production Equipment',
    department: 'Production',
    owner: 'Production Department',
    teamId: 'team1',
    technician: 'John Smith',
    location: 'Building A - Floor 2',
    purchaseDate: '2023-01-15',
    warrantyExpiry: '2026-01-15',
    status: 'operational',
    lastMaintenance: '2024-11-20',
    nextMaintenance: '2025-02-20',
  },
  {
    id: 'eq2',
    name: 'Industrial Generator',
    serialNumber: 'GEN-2024-045',
    category: 'Power Equipment',
    department: 'Facilities',
    owner: 'Facilities Department',
    teamId: 'team2',
    technician: 'Mike Davis',
    location: 'Building B - Basement',
    purchaseDate: '2022-06-10',
    warrantyExpiry: '2025-06-10',
    status: 'operational',
    lastMaintenance: '2024-12-01',
    nextMaintenance: '2025-03-01',
  },
  {
    id: 'eq3',
    name: 'Laptop - Dell XPS 15',
    serialNumber: 'LAP-2024-123',
    category: 'IT Equipment',
    department: 'Engineering',
    owner: 'James Anderson',
    teamId: 'team3',
    technician: 'Alex Wilson',
    location: 'Building A - Floor 3',
    purchaseDate: '2023-09-01',
    warrantyExpiry: '2026-09-01',
    status: 'operational',
    lastMaintenance: '2024-11-15',
    nextMaintenance: '2025-02-15',
  },
  {
    id: 'eq4',
    name: 'Forklift #3',
    serialNumber: 'FLT-2024-007',
    category: 'Material Handling',
    department: 'Warehouse',
    owner: 'Warehouse Department',
    teamId: 'team1',
    technician: 'Sarah Johnson',
    location: 'Warehouse - Zone C',
    purchaseDate: '2022-03-20',
    warrantyExpiry: '2025-03-20',
    status: 'maintenance',
    lastMaintenance: '2024-12-10',
    nextMaintenance: '2025-01-10',
  },
  {
    id: 'eq5',
    name: 'HVAC System #2',
    serialNumber: 'HVAC-2024-032',
    category: 'Climate Control',
    department: 'Facilities',
    owner: 'Facilities Department',
    teamId: 'team2',
    technician: 'Emily Brown',
    location: 'Building A - Roof',
    purchaseDate: '2021-11-05',
    warrantyExpiry: '2024-11-05',
    status: 'operational',
    lastMaintenance: '2024-11-25',
    nextMaintenance: '2025-02-25',
  },
];

export const mockRequests = [
  {
    id: 'req1',
    subject: 'Leaking Oil from Hydraulic System',
    description: 'The CNC machine is leaking hydraulic oil from the main pump area. Needs immediate attention.',
    type: 'corrective',
    priority: 'high',
    status: 'new',
    equipmentId: 'eq1',
    equipmentName: 'CNC Machine #1',
    teamId: 'team1',
    teamName: 'Mechanics',
    assignedTo: null,
    createdBy: 'Production Manager',
    createdAt: '2024-12-26T10:30:00',
    scheduledDate: '2024-12-27T09:00:00',
    duration: null,
    notes: [],
  },
  {
    id: 'req2',
    subject: 'Routine Generator Inspection',
    description: 'Monthly preventive maintenance check for the industrial generator.',
    type: 'preventive',
    priority: 'medium',
    status: 'in-progress',
    equipmentId: 'eq2',
    equipmentName: 'Industrial Generator',
    teamId: 'team2',
    teamName: 'Electricians',
    assignedTo: 'Mike Davis',
    createdBy: 'Facilities Manager',
    createdAt: '2024-12-20T08:00:00',
    scheduledDate: '2024-12-27T14:00:00',
    duration: 2.5,
    notes: [
      { text: 'Started inspection at 2 PM', timestamp: '2024-12-27T14:00:00', user: 'Mike Davis' }
    ],
  },
  {
    id: 'req3',
    subject: 'Laptop Screen Flickering',
    description: 'User reports intermittent screen flickering on Dell XPS laptop.',
    type: 'corrective',
    priority: 'medium',
    status: 'repaired',
    equipmentId: 'eq3',
    equipmentName: 'Laptop - Dell XPS 15',
    teamId: 'team3',
    teamName: 'IT Support',
    assignedTo: 'Alex Wilson',
    createdBy: 'James Anderson',
    createdAt: '2024-12-23T11:15:00',
    scheduledDate: '2024-12-24T10:00:00',
    completedDate: '2024-12-24T11:30:00',
    duration: 1.5,
    notes: [
      { text: 'Diagnosed as loose display cable', timestamp: '2024-12-24T10:30:00', user: 'Alex Wilson' },
      { text: 'Cable reseated and tested successfully', timestamp: '2024-12-24T11:30:00', user: 'Alex Wilson' }
    ],
  },
  {
    id: 'req4',
    subject: 'Forklift Battery Replacement',
    description: 'Forklift battery showing signs of degradation, needs replacement.',
    type: 'corrective',
    priority: 'high',
    status: 'in-progress',
    equipmentId: 'eq4',
    equipmentName: 'Forklift #3',
    teamId: 'team1',
    teamName: 'Mechanics',
    assignedTo: 'Sarah Johnson',
    createdBy: 'Warehouse Supervisor',
    createdAt: '2024-12-25T09:00:00',
    scheduledDate: '2024-12-26T08:00:00',
    duration: null,
    notes: [
      { text: 'Old battery removed, waiting for new battery delivery', timestamp: '2024-12-26T10:00:00', user: 'Sarah Johnson' }
    ],
  },
  {
    id: 'req5',
    subject: 'HVAC Filter Replacement',
    description: 'Scheduled quarterly filter replacement for HVAC system.',
    type: 'preventive',
    priority: 'low',
    status: 'new',
    equipmentId: 'eq5',
    equipmentName: 'HVAC System #2',
    teamId: 'team2',
    teamName: 'Electricians',
    assignedTo: null,
    createdBy: 'Facilities Manager',
    createdAt: '2024-12-26T14:00:00',
    scheduledDate: '2024-12-30T10:00:00',
    duration: null,
    notes: [],
  },
];

export const categories = [
  'Production Equipment',
  'Power Equipment',
  'IT Equipment',
  'Material Handling',
  'Climate Control',
  'Safety Equipment',
  'Office Equipment',
];

export const departments = [
  'Production',
  'Facilities',
  'Engineering',
  'Warehouse',
  'IT',
  'Maintenance',
  'Administration',
];

export const priorities = [
  { value: 'low', label: 'Low', color: 'success' },
  { value: 'medium', label: 'Medium', color: 'warning' },
  { value: 'high', label: 'High', color: 'danger' },
];

export const requestStatuses = [
  { value: 'new', label: 'New', color: 'primary' },
  { value: 'in-progress', label: 'In Progress', color: 'warning' },
  { value: 'repaired', label: 'Repaired', color: 'success' },
  { value: 'scrap', label: 'Scrap', color: 'danger' },
];
